#!/usr/bin/env python3
"""Make publication-style tables for BERT PC sweep reliability tests."""

from __future__ import annotations

import math
import subprocess
from pathlib import Path

import pandas as pd


PROJECT = Path("/scratch/aniluchavez/hippocampal-speaker-semantics")
RESULTS = PROJECT / "results"
CONVERTER = PROJECT / "scripts" / "tex_table_to_docx.py"

ABOVE_CSV = (
    RESULTS
    / "bert_l12_fixed_unbalanced_pc_sweep_rcross_above_null_no_fdr_summary.csv"
)
CEILING_CSV = (
    RESULTS
    / "bert_l12_fixed_unbalanced_pc_sweep_rcross_below_ceiling_no_fdr_summary.csv"
)
TRAIN_TEST_CSV = (
    RESULTS
    / "bert_l12_fixed_pc_sweep_train_test_r2_summary.csv"
)


def mean_sem(mean: float, sem: float, digits: int = 3) -> str:
    if not math.isfinite(mean):
        return "---"
    if not math.isfinite(sem):
        return f"{mean:.{digits}f}"
    return f"${mean:.{digits}f} \\pm {sem:.{digits}f}$"


def num(x: float, digits: int = 3) -> str:
    if not math.isfinite(x):
        return "---"
    return f"{x:.{digits}f}"


def pval(p: float) -> str:
    if not math.isfinite(p):
        return "---"
    if p < 0.0001:
        return "$<0.0001$"
    return f"{p:.4f}"


def tstat(t: float, df: int) -> str:
    if not math.isfinite(t):
        return "---"
    return f"$t({df})={t:.2f}$"


def write_tex(path: Path, caption: str, label: str, header: list[str], rows: list[list[str]], footnote: str) -> None:
    lines = [
        r"\begin{table}[ht]",
        r"\centering",
        r"\small",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\begin{tabular}{" + "l" + "c" * (len(header) - 1) + "}",
        r"\toprule",
        " & ".join(header) + r" \\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(row) + r" \\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            rf"\begin{{flushleft}}\footnotesize",
            footnote,
            r"\end{flushleft}",
            r"\end{table}",
            "",
        ]
    )
    path.write_text("\n".join(lines))


def convert(tex_path: Path) -> None:
    subprocess.run(
        [
            "/scratch/aniluchavez/miniforge3/envs/gpt2_embed/bin/python3",
            str(CONVERTER),
            str(tex_path),
            str(tex_path.with_suffix(".docx")),
        ],
        check=True,
    )


def main() -> None:
    above = pd.read_csv(ABOVE_CSV)
    ceiling = pd.read_csv(CEILING_CSV)
    train_test = pd.read_csv(TRAIN_TEST_CSV)
    above = above.merge(
        train_test[
            [
                "pc",
                "patient_mean_test_r2",
                "patient_sem_test_r2",
                "patient_mean_train_r2",
                "patient_sem_train_r2",
            ]
        ],
        on="pc",
        how="left",
    )

    above_rows = []
    for _, r in above.sort_values("pc").iterrows():
        above_rows.append(
            [
                str(int(r["pc"])),
                mean_sem(r["patient_mean_test_r2"], r["patient_sem_test_r2"]),
                mean_sem(r["patient_mean_train_r2"], r["patient_sem_train_r2"]),
                mean_sem(r["patient_mean_obs_r_cross"], r["patient_diff_sem"]),
                num(r["patient_mean_null_mean"], 3),
                num(r["patient_mean_diff_obs_minus_nullmean"], 3),
                f"{int(r['n_sig_neurons_p05_no_fdr'])}/{int(r['n_neurons'])} ({r['pct_sig_neurons_p05_no_fdr']:.1f}\\%)",
                num(r["patient_wilcoxon_W_greater"], 0),
                pval(r["patient_wilcoxon_p_greater"]),
            ]
        )

    above_tex = RESULTS / "bert_l12_fixed_pc_sweep_rcross_above_null_table.tex"
    write_tex(
        above_tex,
        (
            "BERT L12 fixed-window cross-condition reliability across PCA dimensionalities: "
            "$r_\\mathrm{cross}$ above empirical null."
        ),
        "tab:bert_l12_fixed_pc_sweep_rcross_above_null",
        [
            "PCs",
            "Test $R^2$",
            "Train $R^2$",
            "$r_\\mathrm{cross}$",
            "Null mean",
            "$\\Delta$",
            "Sig. neurons",
            "Wilcoxon $W$",
            "$p$",
        ],
        above_rows,
        (
            "Values are patient means $\\pm$ SEM unless otherwise noted. "
            "$\\Delta$ is observed patient-mean $r_\\mathrm{cross}$ minus the empirical-null mean. "
            "Train and test $R^2$ are encoding pseudo-$R^2$ values from shuffled outer cross-validation. "
            "Patient tests are one-sided Wilcoxon signed-rank tests of $\\Delta>0$ across 15 patients. "
            "Sig. neurons are uncorrected one-sided empirical-null tests at $p<0.05$ based on each neuron's "
            "$r_\\mathrm{cross}$ reliability null distribution, generated by row-permuting embeddings relative "
            "to spikes in the listening/other condition before refitting beta weights; no FDR correction was applied. "
            "Fixed windows used BERT-base L12 with self onset$-200$ ms and other onset$+200$ ms, both 500 ms long."
        ),
    )

    ceiling_rows = []
    for _, r in ceiling.sort_values("pc").iterrows():
        ceiling_rows.append(
            [
                str(int(r["pc"])),
                num(r["patient_mean_r_cross"], 3),
                num(r["patient_mean_ceiling"], 3),
                mean_sem(
                    r["patient_mean_ceiling_minus_rcross"],
                    r["patient_diff_sem"],
                ),
                f"{int(r['n_patients_ceiling_gt_rcross'])}/{int(r['n_patients'])}",
                num(r["patient_wilcoxon_W_greater"], 0),
                pval(r["patient_wilcoxon_p_greater"]),
            ]
        )

    ceiling_tex = RESULTS / "bert_l12_fixed_pc_sweep_rcross_below_ceiling_table.tex"
    write_tex(
        ceiling_tex,
        (
            "BERT L12 fixed-window cross-condition reliability across PCA dimensionalities: "
            "$r_\\mathrm{cross}$ below the reliability ceiling."
        ),
        "tab:bert_l12_fixed_pc_sweep_rcross_below_ceiling",
        [
            "PCs",
            "$r_\\mathrm{cross}$",
            "Ceiling",
            "Ceiling $-$ $r_\\mathrm{cross}$",
            "Patients",
            "Wilcoxon $W$",
            "$p$",
        ],
        ceiling_rows,
        (
            "Values are patient means $\\pm$ SEM unless otherwise noted. "
            "The reliability ceiling is the per-neuron bracket ceiling, "
            "$\\min(r_\\mathrm{speaking}, r_\\mathrm{listening})$, averaged within patient. "
            "Patient tests are one-sided Wilcoxon signed-rank tests of ceiling $>$ $r_\\mathrm{cross}$ across 15 patients. "
            "No FDR correction was applied. "
            "Fixed windows used BERT-base L12 with self onset$-200$ ms and other onset$+200$ ms, both 500 ms long."
        ),
    )

    convert(above_tex)
    convert(ceiling_tex)
    print(above_tex)
    print(above_tex.with_suffix(".docx"))
    print(ceiling_tex)
    print(ceiling_tex.with_suffix(".docx"))


if __name__ == "__main__":
    main()
